name: ondevice_ml
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pytorch_lite: ^4.3.2
  image_picker: ^1.0.7
  camera: ^0.11.0+2
  path_provider: ^2.1.2
  path: ^1.9.0
  permission_handler: ^11.3.0
  get: ^4.6.6
  tflite_flutter: ^0.11.0
  fixnum: ^1.1.1
  protobuf: ^3.1.0
  image: ^4.5.2
  get_storage: ^2.1.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/models/
    - assets/labels/
